import numpy as np
import source, uniform, vortex, doublet


class Uniform:
    """
    Contains information related to a source (or sink).
    """

    def __init__(self, u,v):
        """
        Sets the location and strength of the singularity.

        Parameters
        ----------
        u: float
            velocity ion the x direction
        v: float
            velocity in the y direction
        """
        self.U = u
        self.V = v

    def velocity(self, X, Y):
        """
        Computes the velocity field generated by the singularity.

        Parameters
        ----------
        X: 2D Numpy array of floats
            x-coordinate of the mesh points.
        Y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        u: 2D Numpy array of floats
            x-component of the velocity field generated by the source.
        v: 2D Numpy array of floats
            y-component of the velocity field generated by the source.
        """
        u, v = uniform.get_velocity(self.U, X, Y)
        return u, v

    def stream_function(self, X, Y):
        """
        Computes the stream-function generated by the singularity.

        Parameters
        ----------
        X: 2D Numpy array of floats
            x-coordinate of the mesh points.
        Y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        psi: 2D Numpy array of floats
            Streamfunction generated by the source.
        """
        psi = uniform.get_stream_function(self.U, X, Y)
        return psi


class Source:
    """
    Contains information related to a source (or sink).
    """
    def __init__(self, strength, x, y):
        """
        Sets the location and strength of the singularity.
        
        Parameters
        ----------
        strength: float
            Strength of the singularity.
        x: float
            x-coordinate of the singularity.
        y: float
            y-coordinate of the singularity.
        """
        self.strength = strength
        self.x, self.y = x, y
    
    def velocity(self, X, Y):
        """
        Computes the velocity field generated by the singularity.
        
        Parameters
        ----------
        X: 2D Numpy array of floats
            x-coordinate of the mesh points.
        Y: 2D Numpy array of floats
            y-coordinate of the mesh points.
        
        Returns
        -------
        u: 2D Numpy array of floats
            x-component of the velocity field generated by the source.
        v: 2D Numpy array of floats
            y-component of the velocity field generated by the source.
        """
        u,v=source.get_velocity(self.strength, self.x, self.y, X, Y)
        return u, v
    
    def stream_function(self, X, Y):
        """
        Computes the stream-function generated by the singularity.
        
        Parameters
        ----------
        X: 2D Numpy array of floats
            x-coordinate of the mesh points.
        Y: 2D Numpy array of floats
            y-coordinate of the mesh points.
        
        Returns
        -------
        psi: 2D Numpy array of floats
            Streamfunction generated by the source.
        """
        psi=source.get_stream_function(self.strength, self.x, self.y, X, Y)
        return psi

class Vortex:
    """
    Contains information related to a vortex.
    """

    def __init__(self, strength, x, y):
        """
        Sets the location and strength of the vortex.

        Parameters
        ----------
        strength: float
            Strength of the vortex.
        x: float
            x-coordinate of the vortex.
        y: float
            y-coordinate of the vortex.
        """
        self.strength = strength
        self.x, self.y = x, y

    def velocity(self, X, Y):
        """
        Computes the velocity field generated by the vortex.

        Parameters
        ----------
        X: 2D Numpy array of floats
            x-coordinate of the mesh points.
        Y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        u: 2D Numpy array of floats
            x-component of the velocity field generated by the vortex.
        v: 2D Numpy array of floats
            y-component of the velocity field generated by the vortex.
        """
        u, v = vortex.get_velocity(self.strength, self.x, self.y, X, Y)
        return u, v

    def stream_function(self, X, Y):
        """
        Computes the stream-function generated by the vortex.

        Parameters
        ----------
        X: 2D Numpy array of floats
            x-coordinate of the mesh points.
        Y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        psi: 2D Numpy array of floats
            Streamfunction generated by the vortex.
        """
        psi = vortex.get_stream_function(self.strength, self.x, self.y, X, Y)
        return psi


class doublet:
    """
    Contains information related to a doublet
    """

    def __init__(self, strength, x, y):
        """
        Sets the location and strength of the doublet.

        Parameters
        ----------
        strength: float
            Strength of the singularity.
        x: float
            x-coordinate of the singularity.
        y: float
            y-coordinate of the singularity.
        """
        self.strength = strength
        self.x, self.y = x, y

    def velocity(self, X, Y):
        """
        Computes the velocity field generated by the doublet.

        Parameters
        ----------
        X: 2D Numpy array of floats
            x-coordinate of the mesh points.
        Y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        u: 2D Numpy array of floats
            x-component of the velocity field generated by the doublet.
        v: 2D Numpy array of floats
            y-component of the velocity field generated by the doublet.
        """
        u, v = doublet.get_velocity(self.strength, self.x, self.y, X, Y)
        return u, v

    def stream_function(self, X, Y):
        """
        Computes the stream-function generated by the doublet.

        Parameters
        ----------
        X: 2D Numpy array of floats
            x-coordinate of the mesh points.
        Y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        psi: 2D Numpy array of floats
            Streamfunction generated by the doublet.
        """
        psi = doublet.get_stream_function(self.strength, self.x, self.y, X, Y)
        return psi