import numpy as np



def get_velocity(u_inf, X, Y):
    """
    Returns the velocity field generated by a uniform flow
    
    Parameters
    ----------
    u_inf: float
        free stream velocity.
    X: 2D Numpy array of floats
        x-coordinate of the mesh points.
    Y: 2D Numpy array of floats
        y-coordinate of the mesh points.

    Returns
    -------
    u: 2D Numpy array of floats
        x-component of the velocity vector field.
    v: 2D Numpy array of floats
        y-component of the velocity vector field.
    """
    u = u_inf * np.ones(X.shape)
    v = np.zeros(X.shape)

    return u, v

def get_stream_function(u_inf, X, Y):
    """
    Returns the stream-function generated by a uniform flow.

    Parameters
    ----------
    u_inf: float
        free stream velocity.
    X: 2D Numpy array of floats
        x-coordinate of the mesh points.
    Y: 2D Numpy array of floats
        y-coordinate of the mesh points.

    Returns
    -------
    psi: 2D Numpy array of floats
        The stream-function.
    """
    psi = psi_freestream = u_inf * Y

    return psi